<h1>Produtos</h1>
<div>
    <a href="/produto/adicionar" class="btn btn-success">Adicionar</a>
</div>
<div>
    <table class="table table-responsive">
        <thead>
        <tr>
            <td><b>id</b></td>
            <td><b>Nome</b></td>
            <td><b>Valor</b></td>
            <td><b>Categoria</b></td>
            <td><b>Data Cadastro</b></td>
            <td><b></b></td>
        </tr>
        </thead>
        <tbody>
        <?php if(count($produtos)): ?>
            <?php foreach($produtos as $produto):?>
                <tr>
                    <td><?= $produto->id_produto ?></td>
                    <td><?= $this->escapeHtml($produto->nome_produto) ?></td>
                    <td><?= $this->escapeHtml($produto->valor_produto) ?></td>
                    <td><?= $this->escapeHtml($categorias[$produto->id_categoria_produto]) ?></td>
                    <td><?= date('d/m/Y',strtotime($produto->data_cadastro)) ?></td>
                    <td>
                        <a href="produto/editar/<?= $produto->id_produto ?>" class="btn btn-info">Editar</a>
                        <a href="javascript:if(confirm('Deseja mesmo remover este produto?')) window.location='produto/remover/<?= $produto->id_produto ?>';" class="btn btn-danger">Remover</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="5"><h3>Nenhum produto registrado</h3></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>