<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Bem vindo ao %s Projeto Teste Join %s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><a class="btn btn-success btn-lg" href="/categoria" target="_blank"><?php echo $this->translate('Categorias') ?> &raquo;</a> <a class="btn btn-success btn-lg" href="/produto" target="_blank"><?php echo $this->translate('Produtos') ?> &raquo;</a></p>
</div>